/*
		A basic implementation of the JDialog class.
*/

import java.awt.*;
import javax.swing.*;
import symantec.itools.multimedia.ImageViewer;
import symantec.itools.awt.ImagePanel;
import symantec.itools.awt.ImageHTMLLink;


public class JDialog1 extends javax.swing.JDialog
{
	public JDialog1(Frame parent)
	{
		super(parent);
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		getContentPane().setLayout(null);
		setSize(405,305);
		setVisible(false);
		try {
			imageViewer1.setImageURL(new java.net.URL("http://area23.mond.at/cardpics/talon.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		catch(java.beans.PropertyVetoException e) { }
		getContentPane().add(imageViewer1);
		imageViewer1.setBounds(36,12,132,84);
		try {
			imagePanel1.setImageURL(new java.net.URL("http://area23.mond.at/cardpics/talon.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		catch(java.beans.PropertyVetoException e) { }
		imagePanel1.setLayout(null);
		getContentPane().add(imagePanel1);
		imagePanel1.setBounds(216,12,96,72);
		getContentPane().add(imageHTMLLink1);
		imageHTMLLink1.setBounds(96,192,120,60);
		imageIcon1.setImageObserver(imagePanel1);
		try {
			imageIcon1.setImageLocation(new java.net.URL("http://area23.mond.at/cardpics/talon.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		//$$ imageIcon1.move(180,132);
		//}}
	}

	public JDialog1()
	{
		this((Frame)null);
	}

	public JDialog1(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b)
	{
		if (b)
			setLocation(50, 50);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new JDialog1()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	symantec.itools.multimedia.ImageViewer imageViewer1 = new symantec.itools.multimedia.ImageViewer();
	symantec.itools.awt.ImagePanel imagePanel1 = new symantec.itools.awt.ImagePanel();
	symantec.itools.awt.ImageHTMLLink imageHTMLLink1 = new symantec.itools.awt.ImageHTMLLink();
	com.symantec.itools.javax.swing.icons.ImageIcon imageIcon1 = new com.symantec.itools.javax.swing.icons.ImageIcon();
	//}}

}