import javax.swing.*;
import java.awt.*;
import java.net.*;
import java.util.*;
import java.io.*;
import java.lang.*;
import java.applet.*;
import java.beans.*;
// import ImageViewer;

/**
 * A basic extension of the javax.swing.JApplet class
 */ 
public class JSchnapslet extends JApplet implements java.lang.Runnable
{
    final static String PROTO = "http";
    final static String HOST  = "area23.mond.at";
    final static int    PORT  = 80;
    volatile long errNum = 0; // Errors Ticker
    volatile int ccard; // Computers Card played
    volatile boolean ready = false; // Ready to play
    volatile boolean pSaid = false; // Said something
    URL emptyURL;
    URL backURL;
    URL talonURL;
    volatile game aGame;
    Thread t0;
    
	public void init()
	{
		// Take out this line if you don't use symantec.itools.net.RelativeURL or symantec.itools.awt.util.StatusScroller
		symantec.itools.lang.Context.setApplet(this);
		
		// This line prevents the "Swing: checked access to system event queue" message seen in some browsers.
		getRootPane().putClientProperty("defeatSystemEventQueueCheck", Boolean.TRUE);
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		getContentPane().setLayout(null);
		getContentPane().setFont(new Font("Dialog", Font.PLAIN, 10));
		setSize(504,420);
		
		try { 
		    emptyURL = new URL(PROTO,HOST,PORT,"/cardpics/e.gif");
		    backURL = new URL(PROTO,HOST,PORT,"/cardpics/n0.gif");
		    talonURL = new URL(PROTO,HOST,PORT,"/cardpics/talon.gif");
		} catch (java.net.MalformedURLException error) { }
		javax.swing.
		java.awt.Font schnapsFont = new java.awt.Font("Dialog", Font.PLAIN, 10);
		getContentPane().add(tDbg);
		tDbg.setBounds(0,288,504,132);
		tDbg.setFont(schnapsFont);
		tDbg.setEditable(false);
		pHand.setLayout(null);
		getContentPane().add(pHand);
		pHand.setBounds(0,132,384,108);
		try {
			im1.setImageURL(new java.net.URL("http://area23.mond.at/cardpics/n0.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		catch(java.beans.PropertyVetoException e) { }
		pHand.add(im1);
		im1.setBounds(84,0,72,96);
		try {
			im0.setImageURL(new java.net.URL("http://area23.mond.at/cardpics/n0.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		catch(java.beans.PropertyVetoException e) { }
		pHand.add(im0);
		im0.setBounds(12,0,72,96);
		try {
			im2.setImageURL(new java.net.URL("http://area23.mond.at/cardpics/n0.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		catch(java.beans.PropertyVetoException e) { }
		pHand.add(im2);
		im2.setBounds(156,0,72,96);
		try {
			im3.setImageURL(new java.net.URL("http://area23.mond.at/cardpics/n0.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		catch(java.beans.PropertyVetoException e) { }
		pHand.add(im3);
		im3.setBounds(228,0,72,96);
		try {
			im4.setImageURL(new java.net.URL("http://area23.mond.at/cardpics/n0.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		catch(java.beans.PropertyVetoException e) { }
		pHand.add(im4);
		im4.setBounds(300,0,72,96);
		pGame.setLayout(null);
		getContentPane().add(pGame);
		pGame.setBounds(0,0,384,132);
		try {
			imOut0.setImageURL(new java.net.URL("http://area23.mond.at/cardpics/e.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		catch(java.beans.PropertyVetoException e) { }
		pGame.add(imOut0);
		imOut0.setBounds(96,24,72,96);
		try {
			imOut1.setImageURL(new java.net.URL("http://area23.mond.at/cardpics/e.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		catch(java.beans.PropertyVetoException e) { }
		pGame.add(imOut1);
		imOut1.setBounds(12,12,72,96);
		try {
			imTalon.setImageURL(new java.net.URL("http://area23.mond.at/cardpics/talon.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		catch(java.beans.PropertyVetoException e) { }
		pGame.add(imTalon);
		imTalon.setBounds(204,24,96,72);
		try {
			imAtou.setImageURL(new java.net.URL("http://area23.mond.at/cardpics/n0.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		catch(java.beans.PropertyVetoException e) { }
		pGame.add(imAtou);
		imAtou.setBounds(276,12,72,96);
		pAction.setLayout(null);
		getContentPane().add(pAction);
		pAction.setBounds(384,0,120,240);
		bMerge.setLabel("Start");
		pAction.add(bMerge);
		bMerge.setBackground(java.awt.Color.lightGray);
		bMerge.setBounds(12,0,96,24);
		bMerge.setFont(schnapsFont);
		bStop.setLabel("Ende");
		bStop.setEnabled(false);
		pAction.add(bStop);
		bStop.setBackground(java.awt.Color.lightGray);
		bStop.setBounds(12,24,96,24);
		bStop.setFont(schnapsFont);
		b20b.setLabel("40 Ansagen");
		pAction.add(b20b);
		b20b.setBackground(java.awt.Color.lightGray);
		b20b.setBounds(12,144,96,24);
        b20b.setFont(schnapsFont);
        b20b.setEnabled(false);
        b20a.setLabel("20 Ansagen");
		pAction.add(b20a);
		b20a.setBackground(java.awt.Color.lightGray);
		b20a.setBounds(12,120,96,24);
		b20a.setFont(schnapsFont);
		b20a.setEnabled(false);
		bChange.setLabel("Atou tauschen");
		bChange.setEnabled(false);
		pAction.add(bChange);
		bChange.setBackground(java.awt.Color.lightGray);
		bChange.setBounds(12,168,96,24);
		bChange.setFont(schnapsFont);
		tPoints.setEditable(false);
		tPoints.setText("0");
		tPoints.setFont(schnapsFont);
		pAction.add(tPoints);
		tPoints.setBounds(72,84,36,24);
		bcont.setLabel("WEITER");
		bcont.setEnabled(false);
		pAction.add(bcont);
		bcont.setBackground(java.awt.Color.lightGray);
		bcont.setBounds(12,204,96,24);
		bcont.setFont(schnapsFont);
		pHelp.setLabel("Hilfe");
		pAction.add(pHelp);
		pHelp.setBackground(java.awt.Color.lightGray);
		pHelp.setBounds(12,48,97,24);
		pHelp.setFont(schnapsFont);
		tRest.setEditable(false);
		tRest.setText("10");
		pAction.add(tRest);
		tRest.setBounds(12,84,36,24);
		tRest.setFont(schnapsFont);
		tMes.setEditable(false);
		tMes.setText("Um ein neues Spiel zu beginnen klicken Sie auf Start");
		// tMes.setEnabled(false);
		getContentPane().add(tMes);
		tMes.setFont(schnapsFont);
		tMes.setBounds(12,252,480,24);
        //}}
		t0 = new Thread(this);
		t0.start();
		
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		bStop.addActionListener(lSymAction);
		bMerge.addActionListener(lSymAction);
		bChange.addActionListener(lSymAction);
		SymMouse aSymMouse = new SymMouse();
		im0.addMouseListener(aSymMouse);
		b20a.addActionListener(lSymAction);
		b20b.addActionListener(lSymAction);
		im1.addMouseListener(aSymMouse);
		im2.addMouseListener(aSymMouse);
		im3.addMouseListener(aSymMouse);
		im4.addMouseListener(aSymMouse);
		tMes.addMouseListener(aSymMouse);
		bcont.addActionListener(lSymAction);
		pHelp.addActionListener(lSymAction);
		//}}
	}
	
	//{{DECLARE_CONTROLS
	java.awt.TextArea tDbg = new java.awt.TextArea();
	java.awt.Panel pHand = new java.awt.Panel();
	ImageViewer im1 = new ImageViewer();
	ImageViewer im0 = new ImageViewer();
	ImageViewer im2 = new ImageViewer();
	ImageViewer im3 = new ImageViewer();
	ImageViewer im4 = new ImageViewer();
	java.awt.Panel pGame = new java.awt.Panel();
	ImageViewer imOut0 = new ImageViewer();
	ImageViewer imOut1 = new ImageViewer();
	ImageViewer imTalon = new ImageViewer();
	ImageViewer imAtou = new ImageViewer();
	java.awt.Panel pAction = new java.awt.Panel();
	java.awt.Button bMerge = new java.awt.Button();
	java.awt.Button bStop = new java.awt.Button();
	java.awt.Button b20b = new java.awt.Button();
	java.awt.Button b20a = new java.awt.Button();
	java.awt.Button bChange = new java.awt.Button();
	java.awt.TextField tPoints = new java.awt.TextField();
	java.awt.Button bcont = new java.awt.Button();
	java.awt.Button pHelp = new java.awt.Button();
	java.awt.TextField tRest = new java.awt.TextField();
	java.awt.TextField tMes = new java.awt.TextField();
	//}}



	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == bStop)
				bStop_ActionPerformed(event);
			else if (object == bMerge)
				bMerge_ActionPerformed(event);
			else if (object == bChange)
				bChange_ActionPerformed(event);
			else if (object == b20a)
				b20a_ActionPerformed(event);
			else if (object == b20b)
				b20b_ActionPerformed(event);
			else if (object == bcont)
				bcont_ActionPerformed(event);
			else if (object == pHelp)
				pHelp_ActionPerformed(event);
		}
	}
	
	void errHandler(java.lang.Throwable myErr) {
	    tDbg.append("\nCRITICAL ERROR #"+(++errNum));
	    tDbg.append("\nMessage: "+myErr.getMessage());
	    tDbg.append("\nString: "+myErr.toString());
	    tDbg.append("\nLmessage: "+myErr.getLocalizedMessage()+"\n");
	    myErr.printStackTrace();
	}
	
	void resetButtons(int level) {
        if (level >= 0 ) {
            b20a.setLabel("20 Ansagen");
            b20a.setEnabled(false);
            b20b.setLabel("40 Ansagen");
            b20b.setEnabled(false);
            bChange.setEnabled(false);
        }
        if (level >= 1) {
            bcont.setEnabled(false);
	        if (imTalon.isVisible()==false)
	            imTalon.setVisible(true);  
            try {
                imTalon.setImageURL(talonURL);
                imAtou.setImageURL(emptyURL);
            } catch (java.beans.PropertyVetoException pvex) {
                this.errHandler(pvex);
            }
        }
        if (level >= 2) {        
            try {
                imOut0.setImageURL(emptyURL);
                imOut1.setImageURL(emptyURL);
            } catch (java.beans.PropertyVetoException pvex) {
                this.errHandler(pvex);
            }
        }

	}
	
	void bStop_ActionPerformed(java.awt.event.ActionEvent event)
	{	// to do: code goes here.
		bStop_ActionPerformed_Interaction1(event);
	}

	void bStop_ActionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
	        stopGame(2);
		} catch (Exception e) {
		    this.errHandler(e);
		}
	}
	
    void stopGame(int levela) {
        aGame.stopGame();
        bMerge.setEnabled(true);
        bStop.setEnabled(false);
        this.resetButtons(levela);            
        // startGame();
        showPlayersCards();
	}

	void bMerge_ActionPerformed(java.awt.event.ActionEvent event)
	{   // to do: code goes here.
		bMerge_ActionPerformed_Interaction1(event);
	}

	void bMerge_ActionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
        this.resetButtons(1);
        tDbg.setText("");
        bMerge.setEnabled(false);
        bStop.setEnabled(true);
        startGame();
	}

    void startGame() {  /* Mischen */
        aGame=null;
        aGame = new game();
        tRest.setText("10");
        tPoints.setText(""+aGame.gambler.points);
        showAtouCard();
        gameTurn();
    }
    
    void endTurn() {
        int tmppoints;
        /* IMPLEMENT COMPUTERS STRATEGIE HERE */
        if (aGame.playersTurn) {
            ccard = aGame.computersAnswer();
            try {
                imOut1.setImageURL(aGame.computer.hand[ccard].getPictureUrl());
            } catch (java.beans.PropertyVetoException jbpvex) {
                this.errHandler(jbpvex);
            }
		} else { }
        
        tmppoints = aGame.checkPoints(ccard);
        if (tmppoints > 0) {
            tMes.setText("Ihr Stich mit Punkten "+tmppoints+" ! Klicken Sie auf Weiter !");
        } else { 
            tMes.setText("Computer sticht "+tmppoints+" ! Klicken Sie auf Weiter !"); 
        }
        aGame.computer.hand[ccard] = new card(-1);
		tPoints.setText("" + aGame.gambler.points );
        
        // Assign new cards 
        if (aGame.assignNewCard()==1) {
            /* NOW WE HAVE NO MORE TALON */
            try {
                imTalon.setImageURL(emptyURL);
                imTalon.setVisible(false);
                imAtou.setImageURL(emptyURL);
            } catch (java.beans.PropertyVetoException jbpvex) {
                this.errHandler(jbpvex);
            }               
        }
        tRest.setText(""+(19-aGame.index));
        this.printMes();
        resetButtons(0);
        // RESET SAID
        pSaid = false; aGame.said = 'n';
        
        if (aGame.playersTurn) {
            if (aGame.gambler.points > 65) {
                tMes.setText("Sie haben gewonnen mit "+aGame.gambler.points+" Punkten !");
                this.stopGame(1);
                return;
            }
        } else {
            if (aGame.computer.points > 65) {
                tMes.setText("Computer hat gewonnen mit "+aGame.computer.points+" Punkten !");
                this.stopGame(1);
                return;
            }
        }        

        if (aGame.movs>=20) {
            if (tmppoints>0) {
                this.tMes.setText("Letzter Stich: Sie haben gewonnen !");
            } else tMes.setText("Letzter Stich: Computer hat gewonnen !");
            this.stopGame(1);
            return;
        }

        bcont.setEnabled(true);
        this.ready=false;
    }
        
    
    void gameTurn() {
        try {
            imOut0.setImageURL(emptyURL);
            imOut1.setImageURL(emptyURL);
        } catch (java.beans.PropertyVetoException jbpvex) {
            this.errHandler(jbpvex);
        }
        showPlayersCards();
        pSaid = false; aGame.said = 'n';
        ready = true; 
        
        if (aGame.playersTurn) {
            tMes.setText("Zum Auspielen einfach auf die entsprechende Karte klicken");
            
            // Gibts was zum Ansagen ?
            int a20 = aGame.gambler.has20();
            if (a20 > 0) {
                b20a.setLabel(aGame.printColor(aGame.gambler.handpairs[0])+" ansagen");
                b20a.setEnabled(true);
                if (a20 > 1) {
                    b20b.setLabel(aGame.printColor(aGame.gambler.handpairs[1])+" ansagen");
                    b20b.setEnabled(true);
                } else b20b.setLabel("kein 2. Paar");
            }
            
            // Wann kann man austauschen ?
            if ((aGame.atouIsChangable(aGame.gambler)) && (pSaid==false))
                bChange.setEnabled(true);
        } else { 
        /* COMPUTERS TURN IMPLEMENTIEREN */
            if (aGame.atouIsChangable(aGame.computer)) {
                aGame.changeAtou(aGame.computer);
			    this.showAtouCard();
			    aGame.mqueue.insert("Computer tauscht Atou aus !!!");
			}
            ccard = aGame.computerStarts();
            
            try {
                imOut1.setImageURL(aGame.computer.hand[ccard].getPictureUrl());
            } catch (java.beans.PropertyVetoException jbpvex) {
                this.errHandler(jbpvex);
            }
            tMes.setText("Zum Antworten einfach auf die entsprechende Karte klicken");
        }
        printMes();
	}
    
    void printMes() {
        tDbg.append(aGame.mqueue.fetch());   
    }
    
	void showPlayersCards() {
	    try {
    	    im0.setImageURL(aGame.gambler.hand[0].getPictureUrl());
	        im1.setImageURL(aGame.gambler.hand[1].getPictureUrl());
	        im2.setImageURL(aGame.gambler.hand[2].getPictureUrl());
    	    im3.setImageURL(aGame.gambler.hand[3].getPictureUrl());
	        im4.setImageURL(aGame.gambler.hand[4].getPictureUrl());
	    } catch (java.beans.PropertyVetoException exp) {
            this.errHandler(exp);
	    }
	}
	
	void showAtouCard() {
	    try {
	        imAtou.setImageURL(aGame.set[19].getPictureUrl());
	    } catch (java.beans.PropertyVetoException exp) {
            this.errHandler(exp);
	    }
	}

	void bChange_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		bChange_ActionPerformed_Interaction1(event);
	}

	void bChange_ActionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
			aGame.changeAtou(aGame.gambler);
			this.showAtouCard();
			bChange.setEnabled(false);
			gameTurn();
		} catch (Exception e) {
            this.errHandler(e);		    
		}
	}

	class SymMouse extends java.awt.event.MouseAdapter
	{
		public void mouseClicked(java.awt.event.MouseEvent event)
		{
			Object object = event.getSource();
			if (object == im0) imageMouseEventHandler(event,0);
			else if (object == im1) imageMouseEventHandler(event,1);
			else if (object == im2) imageMouseEventHandler(event,2);
			else if (object == im3)imageMouseEventHandler(event,3);
			else if (object == im4) imageMouseEventHandler(event,4);
		}
	}


	void b20a_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		b20a_ActionPerformed_Interaction1(event);
	}

	void b20a_ActionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
	    
		try {
			if ((pSaid) || (aGame.gambler.handpairs[0]=='n')) return;
			if (aGame.gambler.handpairs[0]==aGame.atouInGame) 
			    aGame.gambler.points+=40;
			else aGame.gambler.points+=20;
			pSaid = true;
			bChange.setEnabled(false);
			aGame.said = aGame.gambler.handpairs[0];
		    aGame.mqueue.insert("Said: "+aGame.said);	
			tPoints.setText("" + aGame.gambler.points);

		} catch (Exception e) {
            this.errHandler(e);
		}
	}

	void b20b_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		b20b_ActionPerformed_Interaction1(event);
	}

	void b20b_ActionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
			if ((pSaid) || (aGame.gambler.handpairs[1]=='n')) return;
			if (aGame.gambler.handpairs[1]==aGame.atouInGame) 
			    aGame.gambler.points+=40;
			else aGame.gambler.points+=20;
			pSaid = true;
			bChange.setEnabled(false);
			aGame.said = aGame.gambler.handpairs[1];
			aGame.mqueue.insert("Said: "+aGame.said);
			tPoints.setText("" + aGame.gambler.points);
		} catch (Exception e) {
		    this.errHandler(e);
		}
	}
	
	void imageMouseEventHandler(java.awt.event.MouseEvent event, int ic)
	{
		try {
		    if (!ready) return;		    
            if (aGame.gambler.hand[ic].isValidCard() == false) {
                aGame.mqueue.insert("Das ist keine gültige Karte !");
                printMes();
                return;		    
            }
		    if (pSaid) 
		        if ((aGame.said == aGame.gambler.hand[ic].getColor()) && 
		            (aGame.gambler.hand[ic].getValue()>2) && 
		            (aGame.gambler.hand[ic].getValue()<5)) {
		                ; // we can continue
		         } else {
                    aGame.mqueue.insert("Sie muessen eine Karte vom Paar ausspielen !");
                    printMes();		            
		            return ;		    
		         }
		    if ((aGame.colorHitRule) && (aGame.playersTurn==false)) {
		        // CORRECT WAY ?
		        if (aGame.gambler.isColorHitValid(ic, aGame.computer.hand[ccard])==false) {
                    aGame.mqueue.insert("Farb und Stichzwang muss eingehalten werden !");		            
                    printMes();
		            return ;
		        }
		    }
		    
		    aGame.playedOut = aGame.gambler.hand[ic];
			// Besser Cards als Array
			switch (ic) {
			    case 0: im0.setImageURL(emptyURL); break;
			    case 1: im1.setImageURL(emptyURL); break;			    
			    case 2: im2.setImageURL(emptyURL); break;			    
			    case 3: im3.setImageURL(emptyURL); break;			    
			    case 4: im4.setImageURL(emptyURL); break;			    
			    default: tDbg.append("Assertion !");
			}
			imOut0.setImageURL(aGame.gambler.hand[ic].getPictureUrl());
		} catch (Exception e) {
            this.errHandler(e);		    
    	}
		aGame.gambler.hand[ic] = new card(-1);		
		ready = false;
		endTurn();
	}
	
	public void run() {
	    
	}

	void bcont_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		bcont_ActionPerformed_Interaction1(event);
	}

	void bcont_ActionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
		    this.ready = true;
			this.gameTurn();
			bcont.setEnabled(false);
		} catch (Exception e) {
            this.errHandler(e);		    
		}
	}

	void pHelp_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		pHelp_ActionPerformed_Interaction1(event);
	}

	void pHelp_ActionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
		    tDbg.append("\n----------------\nPlayer: "+aGame.gambler.showHand());
		    tDbg.append("\nComputer: "+aGame.computer.showHand());
            tDbg.append("\n");			
		} catch (Exception e) {
		}
	}
}
