//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchnapsNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchnapsNet.Properties.Resource_en", typeof(Resource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string action_about {
            get {
                return ResourceManager.GetString("action_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string action_continue {
            get {
                return ResourceManager.GetString("action_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string action_exit {
            get {
                return ResourceManager.GetString("action_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string action_help {
            get {
                return ResourceManager.GetString("action_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load game.
        /// </summary>
        internal static string action_load {
            get {
                return ResourceManager.GetString("action_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string action_options {
            get {
                return ResourceManager.GetString("action_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save game.
        /// </summary>
        internal static string action_save {
            get {
                return ResourceManager.GetString("action_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenShot.
        /// </summary>
        internal static string action_screenshot {
            get {
                return ResourceManager.GetString("action_screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string action_settings {
            get {
                return ResourceManager.GetString("action_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string action_start {
            get {
                return ResourceManager.GetString("action_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string action_stop {
            get {
                return ResourceManager.GetString("action_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schnaps.Net.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atou is {0}!.
        /// </summary>
        internal static string atou_is {
            get {
                return ResourceManager.GetString("atou_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriage 20.
        /// </summary>
        internal static string b20a_text {
            get {
                return ResourceManager.GetString("b20a_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atou marriage 40.
        /// </summary>
        internal static string b20b_text {
            get {
                return ResourceManager.GetString("b20b_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back_button {
            get {
                return ResourceManager.GetString("back_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Atou.
        /// </summary>
        internal static string bChange_text {
            get {
                return ResourceManager.GetString("bChange_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string bContinue_text {
            get {
                return ResourceManager.GetString("bContinue_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best card would be: {0}.
        /// </summary>
        internal static string best_card_would_be {
            get {
                return ResourceManager.GetString("best_card_would_be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string bHelp_text {
            get {
                return ResourceManager.GetString("bHelp_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string bStart_text {
            get {
                return ResourceManager.GetString("bStart_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string bStop_text {
            get {
                return ResourceManager.GetString("bStop_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualStudio 2022 C# 4.8.
        /// </summary>
        internal static string build_with {
            get {
                return ResourceManager.GetString("build_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 hole.
        /// </summary>
        internal static string call_10_hole {
            get {
                return ResourceManager.GetString("call_10_hole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ace beggar.
        /// </summary>
        internal static string call_ace_beggar {
            get {
                return ResourceManager.GetString("call_ace_beggar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beggar.
        /// </summary>
        internal static string call_beggar {
            get {
                return ResourceManager.GetString("call_beggar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default game.
        /// </summary>
        internal static string call_default_game {
            get {
                return ResourceManager.GetString("call_default_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer&apos;s Schnapser.
        /// </summary>
        internal static string call_farmers_schnapser {
            get {
                return ResourceManager.GetString("call_farmers_schnapser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March through.
        /// </summary>
        internal static string call_march_through {
            get {
                return ResourceManager.GetString("call_march_through", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schnapser.
        /// </summary>
        internal static string call_schnapser {
            get {
                return ResourceManager.GetString("call_schnapser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sir&apos;s Schnapser.
        /// </summary>
        internal static string call_sirs_schnapser {
            get {
                return ResourceManager.GetString("call_sirs_schnapser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carddeck.
        /// </summary>
        internal static string carddeck {
            get {
                return ResourceManager.GetString("carddeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten.
        /// </summary>
        internal static string cardval_10 {
            get {
                return ResourceManager.GetString("cardval_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ace.
        /// </summary>
        internal static string cardval_11 {
            get {
                return ResourceManager.GetString("cardval_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jack.
        /// </summary>
        internal static string cardval_2 {
            get {
                return ResourceManager.GetString("cardval_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen.
        /// </summary>
        internal static string cardval_3 {
            get {
                return ResourceManager.GetString("cardval_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King.
        /// </summary>
        internal static string cardval_4 {
            get {
                return ResourceManager.GetString("cardval_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on Continue!.
        /// </summary>
        internal static string click_continue {
            get {
                return ResourceManager.GetString("click_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &apos;Start&apos; button to start a new game..
        /// </summary>
        internal static string clickon_start {
            get {
                return ResourceManager.GetString("clickon_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close game.
        /// </summary>
        internal static string close_game {
            get {
                return ResourceManager.GetString("close_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You failed to close this game, computer wins!.
        /// </summary>
        internal static string closing_failed {
            get {
                return ResourceManager.GetString("closing_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty card.
        /// </summary>
        internal static string color_e {
            get {
                return ResourceManager.GetString("color_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hearts.
        /// </summary>
        internal static string color_h {
            get {
                return ResourceManager.GetString("color_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more cards in talon -&gt; follow the suit led otherwise must trump (if possible)..
        /// </summary>
        internal static string color_hit_force_mode {
            get {
                return ResourceManager.GetString("color_hit_force_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diamonds.
        /// </summary>
        internal static string color_k {
            get {
                return ResourceManager.GetString("color_k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nocolor.
        /// </summary>
        internal static string color_n {
            get {
                return ResourceManager.GetString("color_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spades.
        /// </summary>
        internal static string color_p {
            get {
                return ResourceManager.GetString("color_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clubs.
        /// </summary>
        internal static string color_t {
            get {
                return ResourceManager.GetString("color_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string colorDelimiter {
            get {
                return ResourceManager.GetString("colorDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to computer.
        /// </summary>
        internal static string computer {
            get {
                return ResourceManager.GetString("computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer changes Atou card..
        /// </summary>
        internal static string computer_changes_atou {
            get {
                return ResourceManager.GetString("computer_changes_atou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer closes game!.
        /// </summary>
        internal static string computer_closed_game {
            get {
                return ResourceManager.GetString("computer_closed_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer failed closing the game, you win!.
        /// </summary>
        internal static string computer_closing_failed {
            get {
                return ResourceManager.GetString("computer_closing_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer won with {0} points!.
        /// </summary>
        internal static string computer_has_won_points {
            get {
                return ResourceManager.GetString("computer_has_won_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer hits with {0} points..
        /// </summary>
        internal static string computer_hit_points {
            get {
                return ResourceManager.GetString("computer_hit_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer plays out.
        /// </summary>
        internal static string computer_plays_out {
            get {
                return ResourceManager.GetString("computer_plays_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to computer announces  a marriages in color {0}.
        /// </summary>
        internal static string computer_says_pair {
            get {
                return ResourceManager.GetString("computer_says_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last trick: computer wins!.
        /// </summary>
        internal static string computer_wins_last_hit {
            get {
                return ResourceManager.GetString("computer_wins_last_hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer won tournament. You&apos;re a taylor!.
        /// </summary>
        internal static string computer_won_taylor {
            get {
                return ResourceManager.GetString("computer_won_taylor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer won tournament. You&apos;ve been marked with a fat point..
        /// </summary>
        internal static string computer_won_tournament_ {
            get {
                return ResourceManager.GetString("computer_won_tournament.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to continue..
        /// </summary>
        internal static string continue_ToolTip {
            get {
                return ResourceManager.GetString("continue_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new players.
        /// </summary>
        internal static string creating_players {
            get {
                return ResourceManager.GetString("creating_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default cards.
        /// </summary>
        internal static string default_cards {
            get {
                return ResourceManager.GetString("default_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending game!.
        /// </summary>
        internal static string ending_game {
            get {
                return ResourceManager.GetString("ending_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to english cards.
        /// </summary>
        internal static string english_cards {
            get {
                return ResourceManager.GetString("english_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close game..
        /// </summary>
        internal static string exception_cannot_close_game {
            get {
                return ResourceManager.GetString("exception_cannot_close_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic SchnapsNet application exception..
        /// </summary>
        internal static string exception_generic_schnapsexception {
            get {
                return ResourceManager.GetString("exception_generic_schnapsexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forty and enough !.
        /// </summary>
        internal static string fourty_and_enough {
            get {
                return ResourceManager.GetString("fourty_and_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forty in.
        /// </summary>
        internal static string fourty_in_color {
            get {
                return ResourceManager.GetString("fourty_in_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to french cards.
        /// </summary>
        internal static string french_cards {
            get {
                return ResourceManager.GetString("french_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to german cards.
        /// </summary>
        internal static string german_cards {
            get {
                return ResourceManager.GetString("german_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/heinrichelsigan/schnapslet.
        /// </summary>
        internal static string github_uri {
            get {
                return ResourceManager.GetString("github_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Schnapslet v2.24.1225 - Pre Alpha Release&lt;/h1&gt;
        ///Implementation of the card game Schnapsen as a simple Asp.Net WebApp
        ///by Heinrich Elsigan (&lt;a href=&quot;mailto:he@area23.at&quot;&gt;heinrich.elsigan@area23.at&lt;/a&gt;).
        ///&lt;br /&gt;
        ///Schnapslet is open source under GPL 3 and publicly accessible via &lt;a href=&quot;https://github.com/&quot; target=&quot;_blank&quot;&gt;GitHub&lt;/a&gt; repository &lt;a href=&quot;https://github.com/heinrichelsigan/schnapslet&quot; target=&quot;_blank&quot;&gt;github.com/heinrichelsigan/schnapslet&lt;/a&gt;.
        ///&lt;hr /&gt;
        ///&lt;h2&gt;Functionality:&lt;/h2&gt;
        ///&lt;p&gt;The game is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help_text {
            get {
                return ResourceManager.GetString("help_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player card 1.
        /// </summary>
        internal static string im0_text {
            get {
                return ResourceManager.GetString("im0_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player card 2.
        /// </summary>
        internal static string im1_text {
            get {
                return ResourceManager.GetString("im1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player card 3.
        /// </summary>
        internal static string im2_text {
            get {
                return ResourceManager.GetString("im2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player card 4.
        /// </summary>
        internal static string im3_text {
            get {
                return ResourceManager.GetString("im3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player card 5.
        /// </summary>
        internal static string im4_text {
            get {
                return ResourceManager.GetString("im4_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap deck with fist to start..
        /// </summary>
        internal static string image_fist {
            get {
                return ResourceManager.GetString("image_fist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take half of merged deck to start..
        /// </summary>
        internal static string image_take {
            get {
                return ResourceManager.GetString("image_take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is closed!.
        /// </summary>
        internal static string imageAtou_AltText {
            get {
                return ResourceManager.GetString("imageAtou_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on atou to close game!.
        /// </summary>
        internal static string imageAtou_ToolTip {
            get {
                return ResourceManager.GetString("imageAtou_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to start a new game..
        /// </summary>
        internal static string imageMerge_ToolTip {
            get {
                return ResourceManager.GetString("imageMerge_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atou card.
        /// </summary>
        internal static string imAtou_text {
            get {
                return ResourceManager.GetString("imAtou_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer card 0.
        /// </summary>
        internal static string imgCOut0_text {
            get {
                return ResourceManager.GetString("imgCOut0_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer card 1.
        /// </summary>
        internal static string imgCOut1_text {
            get {
                return ResourceManager.GetString("imgCOut1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer card 2.
        /// </summary>
        internal static string imgCOut2_text {
            get {
                return ResourceManager.GetString("imgCOut2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer card 3.
        /// </summary>
        internal static string imgCOut3_text {
            get {
                return ResourceManager.GetString("imgCOut3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer card 4.
        /// </summary>
        internal static string imgCOut4_text {
            get {
                return ResourceManager.GetString("imgCOut4_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging animation.
        /// </summary>
        internal static string imMerge_text {
            get {
                return ResourceManager.GetString("imMerge_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playout card.
        /// </summary>
        internal static string imOut0_text {
            get {
                return ResourceManager.GetString("imOut0_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer card.
        /// </summary>
        internal static string imOut1_text {
            get {
                return ResourceManager.GetString("imOut1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talon card.
        /// </summary>
        internal static string imTalon_text {
            get {
                return ResourceManager.GetString("imTalon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last trick: you win!.
        /// </summary>
        internal static string last_hit_you_have_won {
            get {
                return ResourceManager.GetString("last_hit_you_have_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string learn_more {
            get {
                return ResourceManager.GetString("learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging cards.
        /// </summary>
        internal static string merging_cards {
            get {
                return ResourceManager.GetString("merging_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new game.
        /// </summary>
        internal static string newgame_starts {
            get {
                return ResourceManager.GetString("newgame_starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no second pair.
        /// </summary>
        internal static string no_second_pair {
            get {
                return ResourceManager.GetString("no_second_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game has been started!.
        /// </summary>
        internal static string nogame_started {
            get {
                return ResourceManager.GetString("nogame_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player closes game!.
        /// </summary>
        internal static string player_closed_game {
            get {
                return ResourceManager.GetString("player_closed_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polish cardset.
        /// </summary>
        internal static string polish_cards {
            get {
                return ResourceManager.GetString("polish_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to say pair.
        /// </summary>
        internal static string say_pair {
            get {
                return ResourceManager.GetString("say_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string sPoints {
            get {
                return ResourceManager.GetString("sPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string sRest {
            get {
                return ResourceManager.GetString("sRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♥.
        /// </summary>
        internal static string symbol_h {
            get {
                return ResourceManager.GetString("symbol_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♦.
        /// </summary>
        internal static string symbol_k {
            get {
                return ResourceManager.GetString("symbol_k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♠.
        /// </summary>
        internal static string symbol_p {
            get {
                return ResourceManager.GetString("symbol_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♣.
        /// </summary>
        internal static string symbol_t {
            get {
                return ResourceManager.GetString("symbol_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string tDbg_text {
            get {
                return ResourceManager.GetString("tDbg_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is no valid card to play!.
        /// </summary>
        internal static string this_is_no_valid_card {
            get {
                return ResourceManager.GetString("this_is_no_valid_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short information.
        /// </summary>
        internal static string tMes_text {
            get {
                return ResourceManager.GetString("tMes_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on card symbol to play out that card..
        /// </summary>
        internal static string toplayout_clickon_card {
            get {
                return ResourceManager.GetString("toplayout_clickon_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string tPoints_text {
            get {
                return ResourceManager.GetString("tPoints_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string tRest_text {
            get {
                return ResourceManager.GetString("tRest_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty and enough!.
        /// </summary>
        internal static string twenty_and_enough {
            get {
                return ResourceManager.GetString("twenty_and_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty in.
        /// </summary>
        internal static string twenty_in_color {
            get {
                return ResourceManager.GetString("twenty_in_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ukraine cardset.
        /// </summary>
        internal static string ukraine_cards {
            get {
                return ResourceManager.GetString("ukraine_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to future_us_cards.
        /// </summary>
        internal static string us_cards {
            get {
                return ResourceManager.GetString("us_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string version_name {
            get {
                return ResourceManager.GetString("version_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/heinrichelsigan/schnapslet/wiki.
        /// </summary>
        internal static string wiki_uri {
            get {
                return ResourceManager.GetString("wiki_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you.
        /// </summary>
        internal static string you {
            get {
                return ResourceManager.GetString("you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win with {0} points!.
        /// </summary>
        internal static string you_have_won_points {
            get {
                return ResourceManager.GetString("you_have_won_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow the suit led stict rules!.
        /// </summary>
        internal static string you_must_play_color_hit_force_rules {
            get {
                return ResourceManager.GetString("you_must_play_color_hit_force_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must play out queen or king when marriages!.
        /// </summary>
        internal static string you_must_play_pair_card {
            get {
                return ResourceManager.GetString("you_must_play_pair_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thou announce a marriages in color {0}!.
        /// </summary>
        internal static string you_say_pair {
            get {
                return ResourceManager.GetString("you_say_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won tournament. Computer lost as a taylor..
        /// </summary>
        internal static string you_won_taylor {
            get {
                return ResourceManager.GetString("you_won_taylor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won tournament. Computer&apos;s marked with a fat point..
        /// </summary>
        internal static string you_won_tournement {
            get {
                return ResourceManager.GetString("you_won_tournement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hit with {0} points.
        /// </summary>
        internal static string your_hit_points {
            get {
                return ResourceManager.GetString("your_hit_points", resourceCulture);
            }
        }
    }
}
