//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchnapsNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchnapsNet.Properties.Resource_fr", typeof(Resource_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information.
        /// </summary>
        internal static string action_about {
            get {
                return ResourceManager.GetString("action_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continuer.
        /// </summary>
        internal static string action_continue {
            get {
                return ResourceManager.GetString("action_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sortie d&apos;application.
        /// </summary>
        internal static string action_exit {
            get {
                return ResourceManager.GetString("action_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aide.
        /// </summary>
        internal static string action_help {
            get {
                return ResourceManager.GetString("action_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obtenir le jeu.
        /// </summary>
        internal static string action_load {
            get {
                return ResourceManager.GetString("action_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        internal static string action_options {
            get {
                return ResourceManager.GetString("action_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sauvegarder la partie.
        /// </summary>
        internal static string action_save {
            get {
                return ResourceManager.GetString("action_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capture d&apos;écran.
        /// </summary>
        internal static string action_screenshot {
            get {
                return ResourceManager.GetString("action_screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paramètres.
        /// </summary>
        internal static string action_settings {
            get {
                return ResourceManager.GetString("action_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to début.
        /// </summary>
        internal static string action_start {
            get {
                return ResourceManager.GetString("action_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replay.
        /// </summary>
        internal static string action_stop {
            get {
                return ResourceManager.GetString("action_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atou c&apos;est {0}!.
        /// </summary>
        internal static string atou_is {
            get {
                return ResourceManager.GetString("atou_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mariage à 20.
        /// </summary>
        internal static string b20a_text {
            get {
                return ResourceManager.GetString("b20a_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mariage à 40.
        /// </summary>
        internal static string b20b_text {
            get {
                return ResourceManager.GetString("b20b_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to précédent.
        /// </summary>
        internal static string back_button {
            get {
                return ResourceManager.GetString("back_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to échanger atou.
        /// </summary>
        internal static string bChange_text {
            get {
                return ResourceManager.GetString("bChange_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continuer.
        /// </summary>
        internal static string bContinue_text {
            get {
                return ResourceManager.GetString("bContinue_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la meilleure carte serait: {0}.
        /// </summary>
        internal static string best_card_would_be {
            get {
                return ResourceManager.GetString("best_card_would_be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aide.
        /// </summary>
        internal static string bHelp_text {
            get {
                return ResourceManager.GetString("bHelp_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to début.
        /// </summary>
        internal static string bStart_text {
            get {
                return ResourceManager.GetString("bStart_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fin.
        /// </summary>
        internal static string bStop_text {
            get {
                return ResourceManager.GetString("bStop_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to another Java or C# compiler.
        /// </summary>
        internal static string build_with {
            get {
                return ResourceManager.GetString("build_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l&apos;origin de cartes.
        /// </summary>
        internal static string carddeck {
            get {
                return ResourceManager.GetString("carddeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dix.
        /// </summary>
        internal static string cardval_10 {
            get {
                return ResourceManager.GetString("cardval_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as.
        /// </summary>
        internal static string cardval_11 {
            get {
                return ResourceManager.GetString("cardval_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valet.
        /// </summary>
        internal static string cardval_2 {
            get {
                return ResourceManager.GetString("cardval_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reine.
        /// </summary>
        internal static string cardval_3 {
            get {
                return ResourceManager.GetString("cardval_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roi.
        /// </summary>
        internal static string cardval_4 {
            get {
                return ResourceManager.GetString("cardval_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neuf.
        /// </summary>
        internal static string cardval_9 {
            get {
                return ResourceManager.GetString("cardval_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cliquez sur continuer!.
        /// </summary>
        internal static string click_continue {
            get {
                return ResourceManager.GetString("click_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on annonce la clôture.
        /// </summary>
        internal static string close_game {
            get {
                return ResourceManager.GetString("close_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to votre clôture manqué, l&apos;ordinateur a gagné!.
        /// </summary>
        internal static string closing_failed {
            get {
                return ResourceManager.GetString("closing_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte vide.
        /// </summary>
        internal static string color_e {
            get {
                return ResourceManager.GetString("color_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coeur.
        /// </summary>
        internal static string color_h {
            get {
                return ResourceManager.GetString("color_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aucune carte dans le talon  -&gt; clôture!.
        /// </summary>
        internal static string color_hit_force_mode {
            get {
                return ResourceManager.GetString("color_hit_force_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carreau.
        /// </summary>
        internal static string color_k {
            get {
                return ResourceManager.GetString("color_k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sans couleur.
        /// </summary>
        internal static string color_n {
            get {
                return ResourceManager.GetString("color_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pique.
        /// </summary>
        internal static string color_p {
            get {
                return ResourceManager.GetString("color_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trèfle.
        /// </summary>
        internal static string color_t {
            get {
                return ResourceManager.GetString("color_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        internal static string colorDelimiter {
            get {
                return ResourceManager.GetString("colorDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ordinateur.
        /// </summary>
        internal static string computer {
            get {
                return ResourceManager.GetString("computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l&apos;ordinateur échange atou..
        /// </summary>
        internal static string computer_changes_atou {
            get {
                return ResourceManager.GetString("computer_changes_atou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l&apos;ordinateur  annonce la clôture!.
        /// </summary>
        internal static string computer_closed_game {
            get {
                return ResourceManager.GetString("computer_closed_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clôture de l&apos;ordinateur manqué, vous avez gagné!.
        /// </summary>
        internal static string computer_closing_failed {
            get {
                return ResourceManager.GetString("computer_closing_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l&apos;ordinateur a gagné avec {0} points!.
        /// </summary>
        internal static string computer_has_won_points {
            get {
                return ResourceManager.GetString("computer_has_won_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l&apos;ordinateur remporte avec {0} points..
        /// </summary>
        internal static string computer_hit_points {
            get {
                return ResourceManager.GetString("computer_hit_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l&apos;ordinateur joue une carte.
        /// </summary>
        internal static string computer_plays_out {
            get {
                return ResourceManager.GetString("computer_plays_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l&apos;ordinateur announce marriage à {0}!.
        /// </summary>
        internal static string computer_says_pair {
            get {
                return ResourceManager.GetString("computer_says_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dernier point: l&apos;ordinateur a gagné!.
        /// </summary>
        internal static string computer_wins_last_hit {
            get {
                return ResourceManager.GetString("computer_wins_last_hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to créer de nouvelles instances de joueur.
        /// </summary>
        internal static string creating_players {
            get {
                return ResourceManager.GetString("creating_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cartes normales.
        /// </summary>
        internal static string default_cards {
            get {
                return ResourceManager.GetString("default_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terminez la partie en cours!.
        /// </summary>
        internal static string ending_game {
            get {
                return ResourceManager.GetString("ending_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cartes d&apos;Angleterre.
        /// </summary>
        internal static string english_cards {
            get {
                return ResourceManager.GetString("english_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarante et finit!.
        /// </summary>
        internal static string fourty_and_enough {
            get {
                return ResourceManager.GetString("fourty_and_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarante en marriage de.
        /// </summary>
        internal static string fourty_in_color {
            get {
                return ResourceManager.GetString("fourty_in_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cartes de France royal.
        /// </summary>
        internal static string french_cards {
            get {
                return ResourceManager.GetString("french_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cartes de Suisse.
        /// </summary>
        internal static string german_cards {
            get {
                return ResourceManager.GetString("german_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/heinrichelsigan/schnapslet/wiki.
        /// </summary>
        internal static string github_uri {
            get {
                return ResourceManager.GetString("github_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schnapslet v2.4.8 (root@darkstar.work)
        ///Jeu de cartes Schnapsen application android de Heinrich Elsigan.
        ///Le jeu est conçu pour jouer contre l&apos;ordinateur. Si c&apos;est votre tour, 
        ///vous pouvez jouer une carte en cliquant sur son icône et en la faisant 
        ///glisser dans le presse-papiers. 
        ///Pour échanger Atou, vous pouvez tirer le Jack Atou sur la carte Atou ci-dessus 
        ///et pour annoncer une paire, vous appelez la reine au roi correspondant 
        ///ou inversement. &quot;échanger&quot; ou &quot;quelques annonces&quot; peuvent également 
        ///êtr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help_text {
            get {
                return ResourceManager.GetString("help_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte 1 de joueur.
        /// </summary>
        internal static string im0_text {
            get {
                return ResourceManager.GetString("im0_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte 2 de joueur.
        /// </summary>
        internal static string im1_text {
            get {
                return ResourceManager.GetString("im1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte 3 de joueur.
        /// </summary>
        internal static string im2_text {
            get {
                return ResourceManager.GetString("im2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte 4 de joueur.
        /// </summary>
        internal static string im3_text {
            get {
                return ResourceManager.GetString("im3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte 5 de joueur.
        /// </summary>
        internal static string im4_text {
            get {
                return ResourceManager.GetString("im4_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte d&apos;atou.
        /// </summary>
        internal static string imAtou_text {
            get {
                return ResourceManager.GetString("imAtou_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte d&apos;ordinateur 0.
        /// </summary>
        internal static string imgCOut0_text {
            get {
                return ResourceManager.GetString("imgCOut0_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte d&apos;ordinateur 1.
        /// </summary>
        internal static string imgCOut1_text {
            get {
                return ResourceManager.GetString("imgCOut1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte d&apos;ordinateur 2.
        /// </summary>
        internal static string imgCOut2_text {
            get {
                return ResourceManager.GetString("imgCOut2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte d&apos;ordinateur 3.
        /// </summary>
        internal static string imgCOut3_text {
            get {
                return ResourceManager.GetString("imgCOut3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte d&apos;ordinateur 4.
        /// </summary>
        internal static string imgCOut4_text {
            get {
                return ResourceManager.GetString("imgCOut4_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animation de fusion.
        /// </summary>
        internal static string imMerge_text {
            get {
                return ResourceManager.GetString("imMerge_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte à jouer.
        /// </summary>
        internal static string imOut0_text {
            get {
                return ResourceManager.GetString("imOut0_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte de réponse.
        /// </summary>
        internal static string imOut1_text {
            get {
                return ResourceManager.GetString("imOut1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carte de talon.
        /// </summary>
        internal static string imTalon_text {
            get {
                return ResourceManager.GetString("imTalon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dernier point: vous avez gagné!.
        /// </summary>
        internal static string last_hit_you_have_won {
            get {
                return ResourceManager.GetString("last_hit_you_have_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en  savoir plus.
        /// </summary>
        internal static string learn_more {
            get {
                return ResourceManager.GetString("learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mélanger des cartes.
        /// </summary>
        internal static string merging_cards {
            get {
                return ResourceManager.GetString("merging_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nouvelle partie a commencé.
        /// </summary>
        internal static string newgame_starts {
            get {
                return ResourceManager.GetString("newgame_starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pas de 2ème paire.
        /// </summary>
        internal static string no_second_pair {
            get {
                return ResourceManager.GetString("no_second_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aucune partie commencée!!.
        /// </summary>
        internal static string nogame_started {
            get {
                return ResourceManager.GetString("nogame_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to joueur annonce la clôture!.
        /// </summary>
        internal static string player_closed_game {
            get {
                return ResourceManager.GetString("player_closed_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cartes de Bologne.
        /// </summary>
        internal static string polish_cards {
            get {
                return ResourceManager.GetString("polish_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to annonce mariage.
        /// </summary>
        internal static string say_pair {
            get {
                return ResourceManager.GetString("say_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        internal static string sPoints {
            get {
                return ResourceManager.GetString("sPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rest.
        /// </summary>
        internal static string sRest {
            get {
                return ResourceManager.GetString("sRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ceci n&apos;est pas une carte valide!.
        /// </summary>
        internal static string this_is_no_valid_card {
            get {
                return ResourceManager.GetString("this_is_no_valid_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info-bulle.
        /// </summary>
        internal static string tMes_text {
            get {
                return ResourceManager.GetString("tMes_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pour jouer, il vous suffit de cliquer sur la carte appropriée.
        /// </summary>
        internal static string toplayout_clickon_card {
            get {
                return ResourceManager.GetString("toplayout_clickon_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string tPoints_text {
            get {
                return ResourceManager.GetString("tPoints_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string tRest_text {
            get {
                return ResourceManager.GetString("tRest_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vingt et finit!.
        /// </summary>
        internal static string twenty_and_enough {
            get {
                return ResourceManager.GetString("twenty_and_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vingt en marriage de.
        /// </summary>
        internal static string twenty_in_color {
            get {
                return ResourceManager.GetString("twenty_in_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cartes de Minsk.
        /// </summary>
        internal static string ukraine_cards {
            get {
                return ResourceManager.GetString("ukraine_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cartes futuristes des Etas-Unis.
        /// </summary>
        internal static string us_cards {
            get {
                return ResourceManager.GetString("us_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous.
        /// </summary>
        internal static string you {
            get {
                return ResourceManager.GetString("you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous avez gagné avec {0} points!.
        /// </summary>
        internal static string you_have_won_points {
            get {
                return ResourceManager.GetString("you_have_won_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clôture doive être respecté!.
        /// </summary>
        internal static string you_must_play_color_hit_force_rules {
            get {
                return ResourceManager.GetString("you_must_play_color_hit_force_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous devez jouer une carte de la mariage!.
        /// </summary>
        internal static string you_must_play_pair_card {
            get {
                return ResourceManager.GetString("you_must_play_pair_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous annoucez mariage à {0}!.
        /// </summary>
        internal static string you_say_pair {
            get {
                return ResourceManager.GetString("you_say_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous remportez la main avec {0} points..
        /// </summary>
        internal static string your_hit_points {
            get {
                return ResourceManager.GetString("your_hit_points", resourceCulture);
            }
        }
    }
}
