//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchnapsNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchnapsNet.Properties.Resource_de", typeof(Resource_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string action_about {
            get {
                return ResourceManager.GetString("action_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        internal static string action_continue {
            get {
                return ResourceManager.GetString("action_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string action_exit {
            get {
                return ResourceManager.GetString("action_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        internal static string action_help {
            get {
                return ResourceManager.GetString("action_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel laden.
        /// </summary>
        internal static string action_load {
            get {
                return ResourceManager.GetString("action_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionen.
        /// </summary>
        internal static string action_options {
            get {
                return ResourceManager.GetString("action_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel speichern.
        /// </summary>
        internal static string action_save {
            get {
                return ResourceManager.GetString("action_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildschirmfoto.
        /// </summary>
        internal static string action_screenshot {
            get {
                return ResourceManager.GetString("action_screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string action_settings {
            get {
                return ResourceManager.GetString("action_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string action_start {
            get {
                return ResourceManager.GetString("action_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neustart.
        /// </summary>
        internal static string action_stop {
            get {
                return ResourceManager.GetString("action_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atou ist {0}!.
        /// </summary>
        internal static string atou_is {
            get {
                return ResourceManager.GetString("atou_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ansagen.
        /// </summary>
        internal static string b20a_text {
            get {
                return ResourceManager.GetString("b20a_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ansagen.
        /// </summary>
        internal static string b20b_text {
            get {
                return ResourceManager.GetString("b20b_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        internal static string back_button {
            get {
                return ResourceManager.GetString("back_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atou tauschen.
        /// </summary>
        internal static string bChange_text {
            get {
                return ResourceManager.GetString("bChange_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        internal static string bContinue_text {
            get {
                return ResourceManager.GetString("bContinue_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beste Karte wäre: {0}.
        /// </summary>
        internal static string best_card_would_be {
            get {
                return ResourceManager.GetString("best_card_would_be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        internal static string bHelp_text {
            get {
                return ResourceManager.GetString("bHelp_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string bStart_text {
            get {
                return ResourceManager.GetString("bStart_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende.
        /// </summary>
        internal static string bStop_text {
            get {
                return ResourceManager.GetString("bStop_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erzeugt mit VisualStudio 2022.
        /// </summary>
        internal static string build_with {
            get {
                return ResourceManager.GetString("build_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartendeck.
        /// </summary>
        internal static string carddeck {
            get {
                return ResourceManager.GetString("carddeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zehn.
        /// </summary>
        internal static string cardval_10 {
            get {
                return ResourceManager.GetString("cardval_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ass.
        /// </summary>
        internal static string cardval_11 {
            get {
                return ResourceManager.GetString("cardval_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bube.
        /// </summary>
        internal static string cardval_2 {
            get {
                return ResourceManager.GetString("cardval_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dame.
        /// </summary>
        internal static string cardval_3 {
            get {
                return ResourceManager.GetString("cardval_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to König.
        /// </summary>
        internal static string cardval_4 {
            get {
                return ResourceManager.GetString("cardval_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie auf Weiter !.
        /// </summary>
        internal static string click_continue {
            get {
                return ResourceManager.GetString("click_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicke auf &apos;Start&apos; um ein neues Spiel zu starten..
        /// </summary>
        internal static string clickon_start {
            get {
                return ResourceManager.GetString("clickon_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zudrehen.
        /// </summary>
        internal static string close_game {
            get {
                return ResourceManager.GetString("close_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zudrehen fehlgeschlagen, Computer hat gewonnen !.
        /// </summary>
        internal static string closing_failed {
            get {
                return ResourceManager.GetString("closing_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leerkarte.
        /// </summary>
        internal static string color_e {
            get {
                return ResourceManager.GetString("color_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♥.
        /// </summary>
        internal static string color_h {
            get {
                return ResourceManager.GetString("color_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Karten im Talon -&gt; Farb- und Stichzwang !.
        /// </summary>
        internal static string color_hit_force_mode {
            get {
                return ResourceManager.GetString("color_hit_force_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♦.
        /// </summary>
        internal static string color_k {
            get {
                return ResourceManager.GetString("color_k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Karte.
        /// </summary>
        internal static string color_n {
            get {
                return ResourceManager.GetString("color_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♠.
        /// </summary>
        internal static string color_p {
            get {
                return ResourceManager.GetString("color_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♣.
        /// </summary>
        internal static string color_t {
            get {
                return ResourceManager.GetString("color_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  in .
        /// </summary>
        internal static string colorDelimiter {
            get {
                return ResourceManager.GetString("colorDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string computer {
            get {
                return ResourceManager.GetString("computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer tauscht Atou aus..
        /// </summary>
        internal static string computer_changes_atou {
            get {
                return ResourceManager.GetString("computer_changes_atou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer dreht zu !.
        /// </summary>
        internal static string computer_closed_game {
            get {
                return ResourceManager.GetString("computer_closed_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zudrehen des Computers fehlgeschlagen, sie haben gewonnen !.
        /// </summary>
        internal static string computer_closing_failed {
            get {
                return ResourceManager.GetString("computer_closing_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer hat mit {0} Punkten gewonnen!.
        /// </summary>
        internal static string computer_has_won_points {
            get {
                return ResourceManager.GetString("computer_has_won_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer sticht mit {0} Punkten..
        /// </summary>
        internal static string computer_hit_points {
            get {
                return ResourceManager.GetString("computer_hit_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer spielt aus.
        /// </summary>
        internal static string computer_plays_out {
            get {
                return ResourceManager.GetString("computer_plays_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer sagt Paar in {0} an!.
        /// </summary>
        internal static string computer_says_pair {
            get {
                return ResourceManager.GetString("computer_says_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzter Stich: Computer hat gewonnen !.
        /// </summary>
        internal static string computer_wins_last_hit {
            get {
                return ResourceManager.GetString("computer_wins_last_hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bekommst einen Schneider..
        /// </summary>
        internal static string computer_won_taylor {
            get {
                return ResourceManager.GetString("computer_won_taylor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bekommst ein Bummerl..
        /// </summary>
        internal static string computer_won_tournement {
            get {
                return ResourceManager.GetString("computer_won_tournement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken sie hier auf weiter!.
        /// </summary>
        internal static string continue_ToolTip {
            get {
                return ResourceManager.GetString("continue_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erzeuge neuer Spieler Instanzen.
        /// </summary>
        internal static string creating_players {
            get {
                return ResourceManager.GetString("creating_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Kartendeck.
        /// </summary>
        internal static string default_cards {
            get {
                return ResourceManager.GetString("default_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beende das aktuelle Spiel.
        /// </summary>
        internal static string ending_game {
            get {
                return ResourceManager.GetString("ending_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 und genug !.
        /// </summary>
        internal static string fourty_and_enough {
            get {
                return ResourceManager.GetString("fourty_and_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vierzig in.
        /// </summary>
        internal static string fourty_in_color {
            get {
                return ResourceManager.GetString("fourty_in_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Französisches Kartendeck.
        /// </summary>
        internal static string french_cards {
            get {
                return ResourceManager.GetString("french_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppeldeutsches Kartendeck.
        /// </summary>
        internal static string german_cards {
            get {
                return ResourceManager.GetString("german_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/heinrichelsigan/schnapslet/wiki.
        /// </summary>
        internal static string github_uri {
            get {
                return ResourceManager.GetString("github_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schnapslet v2.4.23 - Pre Alpha Release 
        ///Implementierung des Kartenspiel Schnapsen als einfache Asp.Net WebApp
        ///von Heinrich Elsigan (heinrich.elsigan@area23.at)
        ///
        ///Funktionsweise:
        ///Das Spiel ist so angelegt, dass man gegen den Computer spielt.
        ///Ist man am Zug, so kann man eine Karte ausspielen, indem man auf das Kartensymbol klickt.
        ///Andere Optionen, wie &quot;Atou austauschen&quot; oder &quot;Ein Paar Ansagen&quot; sind 
        ///ueber die Buttons unterhalb der Kartensymbole moeglich; 
        ///diese Optionen muessen gewaehlt werden, bevor  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help_text {
            get {
                return ResourceManager.GetString("help_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draufklopfen!.
        /// </summary>
        internal static string image_fist {
            get {
                return ResourceManager.GetString("image_fist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abheben!.
        /// </summary>
        internal static string image_take {
            get {
                return ResourceManager.GetString("image_take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel ist zugedreht..
        /// </summary>
        internal static string imageAtou_AltText {
            get {
                return ResourceManager.GetString("imageAtou_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Atou klicken für Zudrehen..
        /// </summary>
        internal static string imageAtou_ToolTip {
            get {
                return ResourceManager.GetString("imageAtou_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier klicken um ein Spiel zu starten..
        /// </summary>
        internal static string imageMerge_ToolTip {
            get {
                return ResourceManager.GetString("imageMerge_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzter Stich: Sie haben gewonnen !.
        /// </summary>
        internal static string last_hit_you_have_won {
            get {
                return ResourceManager.GetString("last_hit_you_have_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr erfahren.
        /// </summary>
        internal static string learn_more {
            get {
                return ResourceManager.GetString("learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mische Karten.
        /// </summary>
        internal static string merging_cards {
            get {
                return ResourceManager.GetString("merging_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Spiel started.
        /// </summary>
        internal static string newgame_starts {
            get {
                return ResourceManager.GetString("newgame_starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kein 2. Paar.
        /// </summary>
        internal static string no_second_pair {
            get {
                return ResourceManager.GetString("no_second_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Spiel gestartet!.
        /// </summary>
        internal static string nogame_started {
            get {
                return ResourceManager.GetString("nogame_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler dreht zu !.
        /// </summary>
        internal static string player_closed_game {
            get {
                return ResourceManager.GetString("player_closed_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polnische Karten.
        /// </summary>
        internal static string polish_cards {
            get {
                return ResourceManager.GetString("polish_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ansagen.
        /// </summary>
        internal static string say_pair {
            get {
                return ResourceManager.GetString("say_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkte.
        /// </summary>
        internal static string sPoints {
            get {
                return ResourceManager.GetString("sPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string sRest {
            get {
                return ResourceManager.GetString("sRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ist keine gültige Karte !.
        /// </summary>
        internal static string this_is_no_valid_card {
            get {
                return ResourceManager.GetString("this_is_no_valid_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum Auspielen einfach auf die entsprechende Karte klicken.
        /// </summary>
        internal static string toplayout_clickon_card {
            get {
                return ResourceManager.GetString("toplayout_clickon_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 und genug !.
        /// </summary>
        internal static string twenty_and_enough {
            get {
                return ResourceManager.GetString("twenty_and_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwanzig in.
        /// </summary>
        internal static string twenty_in_color {
            get {
                return ResourceManager.GetString("twenty_in_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine Konfliktdeck.
        /// </summary>
        internal static string ukraine_cards {
            get {
                return ResourceManager.GetString("ukraine_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du.
        /// </summary>
        internal static string you {
            get {
                return ResourceManager.GetString("you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben mit {0} Punkten gewonnen!.
        /// </summary>
        internal static string you_have_won_points {
            get {
                return ResourceManager.GetString("you_have_won_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farb und Stichzwang muss eingehalten werden !.
        /// </summary>
        internal static string you_must_play_color_hit_force_rules {
            get {
                return ResourceManager.GetString("you_must_play_color_hit_force_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie muessen eine Karte vom Paar ausspielen !.
        /// </summary>
        internal static string you_must_play_pair_card {
            get {
                return ResourceManager.GetString("you_must_play_pair_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sagen Paar in {0} an!.
        /// </summary>
        internal static string you_say_pair {
            get {
                return ResourceManager.GetString("you_say_pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer bekommt einen Schneider..
        /// </summary>
        internal static string you_won_taylor {
            get {
                return ResourceManager.GetString("you_won_taylor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer bekommt ein Bummerl..
        /// </summary>
        internal static string you_won_tournement {
            get {
                return ResourceManager.GetString("you_won_tournement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Stich mit {0} Punkten..
        /// </summary>
        internal static string your_hit_points {
            get {
                return ResourceManager.GetString("your_hit_points", resourceCulture);
            }
        }
    }
}
